# Generated by Django 4.2.7 on 2026-04-29 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (от 7 до 15 цифр).', regex='^\\+?[0-9\\s\\-\\(\\)]{7,15}$')], verbose_name='Телефон')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Текст обращения')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('version', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
