# Generated by Django 4.2.7 on 2026-04-20 15:52

import core.fields
import core.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Основной текст')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткий анонс')),
                ('image', core.fields.MediaImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='news/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'ordering': ['-created_at'],
            },
        ),
    ]
