# Generated by Django 4.2.7 on 2026-04-28 12:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=core.fields.MediaImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
