# Generated by Django 4.2.7 on 2026-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_active', '-created_at'], name='news_is_acti_966dea_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug', 'is_active'], name='news_slug_480a3b_idx'),
        ),
    ]
