# Generated by Django 4.2.7 on 2026-04-29 17:16

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_created_at_alter_news_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=core.fields.MediaImageField(blank=True, formats=['JPEG', 'JPG', 'PNG', 'SVG'], max_size=None, max_upload_size=5242880, null=True, quality=85, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
