# Generated by Django 4.2.7 on 2026-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('slug', models.SlugField(help_text='URL-часть страницы (автоматически генерируется из названия)', unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Текстовое содержимое')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Заголовок (meta title)')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Описание (meta description)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO Ключевые слова (meta keywords)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'db_table': 'pages',
                'ordering': ['title'],
            },
        ),
    ]
