# Generated by Django 4.2.7 on 2026-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
