# Generated by Django 4.2.7 on 2026-04-20 15:52

import core.fields
import core.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('purchase', 'Покупка лома'), ('dismantling', 'Демонтаж'), ('self_transport', 'Самовывоз'), ('production', 'Производство'), ('sales', 'Продажа'), ('consulting', 'Консультации')], max_length=100, verbose_name='Категория')),
                ('image', core.fields.MediaImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='services/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size], verbose_name='Основное изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
    ]
