# Generated by Django 4.2.7 on 2026-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('purchase', 'Покупка лома'), ('dismantling', 'Демонтаж'), ('self_transport', 'Самовывоз'), ('production', 'Производство'), ('sales', 'Продажа'), ('consulting', 'Консультации')], db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'name'], name='services_se_is_acti_4af435_idx'),
        ),
    ]
