# Generated by Django 4.2.7 on 2026-04-29 17:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=core.fields.MediaImageField(blank=True, formats=['JPEG', 'JPG', 'PNG', 'SVG'], max_size=(1920, 1080), max_upload_size=5242880, null=True, quality=85, upload_to='services/', verbose_name='Изображение'),
        ),
    ]
